//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIFirstProgram.DB_Contex
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Mob { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string City { get; set; }
    }
}
